name: online-learning-platform
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/ main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: npm ci
      - name: Linting
        run: npm run lint

  # deploy:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v2
  #       run: npm ci
  #     - name: Production Migration
  #       run: npm run migrate:deploy
